[[Rscape]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5640631b321c66cd3971033dc942ca8990c38519"
libc = "glibc"
os = "linux"

    [[Rscape.download]]
    sha256 = "a4049bcc643a794662ee5e898a80bb5df2d9e06e80c5da272ae8685ca71a55b6"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Rscape]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "692093396059f125d20dd933f6118f89c70d21de"
libc = "glibc"
os = "linux"

    [[Rscape.download]]
    sha256 = "8bbeb0bbb58e01a0cc48b5c333de6fb6632b89c2f81ba661edb0f1f17e4a1af0"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Rscape]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c069e89ea3fe9e04c28710b000e0329da3dca850"
libc = "musl"
os = "linux"

    [[Rscape.download]]
    sha256 = "67397c79293521ed573939b958df6a0b6a685d08fdf57f9b8fe0646001f3a4b3"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.i686-linux-musl-cxx03.tar.gz"
[[Rscape]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfc801547f6fa4c4f6013c0e80ef9c9e0c2340e5"
libc = "musl"
os = "linux"

    [[Rscape.download]]
    sha256 = "daae67a2aaff9e102e14326e264f526863d0edc294b2042b4485b8c7ff5ea8b1"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.i686-linux-musl-cxx11.tar.gz"
[[Rscape]]
arch = "x86_64"
git-tree-sha1 = "d5ba0d7c1097c4a2ab7157de827982271cb2a70a"
os = "macos"

    [[Rscape.download]]
    sha256 = "9cbdde932b226759f6efb8e636db3947f063a7e1beb820044b25619a1505452a"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-apple-darwin.tar.gz"
[[Rscape]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ae85b54d5a9f6755f693e9de3b91a3be6527c03"
libc = "glibc"
os = "linux"

    [[Rscape.download]]
    sha256 = "f8d5ed09d57c2b8ef947de1b1c0a86d06835ec3986b4fe9b296e646e0c2209e6"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Rscape]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d9fe63abf06951607f7fb21486c315700d821cb"
libc = "glibc"
os = "linux"

    [[Rscape.download]]
    sha256 = "3c2a2ccfdc9490233b421821d10d3254f347f38de073ca593f46492c5c57f89e"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Rscape]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eef5000a43d0c1e5b532658db4153ccaa65fc12"
libc = "musl"
os = "linux"

    [[Rscape.download]]
    sha256 = "c6d969e0f77437cda875648df928287c62bf844cb4ed4ff31a49cb5d1db9412a"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Rscape]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ddd26a467e1f3f7d5eea518b1bb33cb6133ba5d"
libc = "musl"
os = "linux"

    [[Rscape.download]]
    sha256 = "be7169dd5ffce25dba6999076a90a1c4f5168adefaad4e42c30d3baa5f647510"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Rscape]]
arch = "x86_64"
git-tree-sha1 = "08388630904b43e37743a3fd0a3a02b2068cda8c"
os = "freebsd"

    [[Rscape.download]]
    sha256 = "6cf314bc38f401b3132444b5e9ff510b30420c2c32beb379172af8f7b0551c2e"
    url = "https://github.com/JuliaBinaryWrappers/Rscape_jll.jl/releases/download/Rscape-v2.0.0+1/Rscape.v2.0.0.x86_64-unknown-freebsd.tar.gz"
